services:
  app:
    build:
      context: .
      target: development
    container_name: vax-app
    ports:
      - "${PORT}:3000"
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
  
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
  
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis