services:
  test-app:
    build:
      context: .
      target: testing
    container_name: test-app
    ports:
      - "${PORT}:3500"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - PORT=${PORT}
      - DB_URL=${DB_URL}
    env_file:
      - ./.env.test
    depends_on:
      test-postgres:
        condition: service_healthy
      test-redis:
        condition: service_started
    # networks:
    #   - vax
    command: npm run test
  
  test-postgres:
    image: postgres:16.2
    restart: always
    container_name: test-postgres
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5433
  
  test-redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6380